import { createSlice } from "@reduxjs/toolkit";
import { v4 as uuidv4 } from 'uuid';

const initialState = {
    currentUserIndex: 0,
    users: [
        {
            id: uuidv4(),
            name: 'Виктор',
            prename: 'Иванов',
            age: 25,
            photo: require('../assets/profilesPhoto/myPhoto.jpg'),
            country: "Россия",
            height: "180 см",
            weight: "75 кг",
            eyeColor: "Карие",
            hairColor: "Темные",
            goal: "Серьезные отношения",
            about: "Люблю путешествовать и заниматься спортом. Открыт для новых знакомств.",
            category: "topDating",
        },
        {
            id: uuidv4(),
            name: 'Марина',
            prename: 'Иванов',
            age: 19,
            photo: require('../assets/profilesPhoto/topwoman1.png'),
            country: "Россия",
            height: "165 см",
            weight: "55 кг",
            eyeColor: "Голубые",
            hairColor: "Светлые",
            goal: "Дружба и отношения",
            about: "Очень люблю животных и природу, обожаю читать книги.",
            category: "topDating",
        },
        {
            id: uuidv4(),
            name: 'Алексей',
            prename: 'Иванов',
            age: 25,
            photo: require('../assets/profilesPhoto/topman2.png'),
            country: "Россия",
            height: "185 см",
            weight: "80 кг",
            eyeColor: "Зеленые",
            hairColor: "Русые",
            goal: "Дружба",
            about: "Привет! Я люблю кататься на велосипеде и изучать новые языки.",
            category: "topDating",
        },
        {
            id: uuidv4(),
            name: 'Виктория',
            prename: 'Иванов',
            age: 18,
            photo: require('../assets/profilesPhoto/topwoman2.png'),
            country: "Россия",
            height: "170 см",
            weight: "50 кг",
            eyeColor: "Карие",
            hairColor: "Черные",
            goal: "Легкие отношения",
            about: "Студентка, люблю кино и общение с интересными людьми.",
            category: "topDating",
        },
        {
            id: uuidv4(),
            name: 'Максим',
            prename: 'Иванов',
            age: 24,
            photo: require('../assets/profilesPhoto/topman3.png'),
            country: "Россия",
            height: "178 см",
            weight: "77 кг",
            eyeColor: "Серые",
            hairColor: "Каштановые",
            goal: "Серьезные отношения",
            about: "Обожаю путешествия, спорт и встречи с друзьями.",
            category: "topDating",
        },
        {

            id: uuidv4(),
            name: 'Марина',
            prename: 'Смирнова',
            age: 25,
            photo: require('../assets/profilesPhoto/lfb1.png'),
            country: "Украина",
            height: "175 см",
            weight: "65 кг",
            eyeColor: "Карие",
            hairColor: "Темные",
            goal: "Серьезные отношения",
            about: "Я люблю активный отдых и всегда ищу возможности для саморазвития.",
            category: "lookingForBoyfriend",
        },
        {
            id: uuidv4(),
            name: 'Алёна',
            prename: 'Смирнова',
            age: 20,
            photo: require('../assets/profilesPhoto/lfb2.png'),
            country: "Украина",
            height: "160 см",
            weight: "53 кг",
            eyeColor: "Голубые",
            hairColor: "Светлые",
            goal: "Дружба и отношения",
            about: "Я творческий человек, люблю искусство и природу.",
            category: "lookingForBoyfriend",
        },
        {
            id: uuidv4(),
            name: 'Марина',
            prename: 'Смирнова',
            age: 19,
            photo: require('../assets/profilesPhoto/topwoman1.png'),
            country: "Украина",
            height: "168 см",
            weight: "58 кг",
            eyeColor: "Зеленые",
            hairColor: "Светлые",
            goal: "Знакомства и отношения",
            about: "Обожаю музыку и путешествия, ищу интересных людей для общения.",
            category: "lookingForBoyfriend",
        },
        {
            id: uuidv4(),
            name: 'Виктория',
            prename: 'Смирнова',
            age: 18,
            photo: require('../assets/profilesPhoto/topwoman2.png'),
            country: "Украина",
            height: "162 см",
            weight: "50 кг",
            eyeColor: "Карие",
            hairColor: "Черные",
            goal: "Легкие отношения",
            about: "Я молода, жизнерадостна, люблю встречать новых людей.",
            category: "lookingForBoyfriend",
        },
        {
            id: uuidv4(),
            name: 'Маргарита',
            prename: 'Смирнова',
            age: 26,
            photo: require('../assets/profilesPhoto/lfb3.png'),
            country: "Украина",
            height: "174 см",
            weight: "63 кг",
            eyeColor: "Серые",
            hairColor: "Русые",
            goal: "Дружба и отношения",
            about: "Люблю фотографию и прогулки на природе.",
            category: "lookingForBoyfriend",
        },
        {
            id: uuidv4(),
            name: 'Виктор',
            prename: 'Петров',
            age: 30,
            photo: require('../assets/profilesPhoto/man1.png'),
            country: "США",
            height: "185 см",
            weight: "85 кг",
            eyeColor: "Карие",
            hairColor: "Черные",
            goal: "Серьезные отношения",
            about: "Я работаю инженером и увлекаюсь спортом, особенно баскетболом.",
            category: "lookingForGirlfriend",
        },
        {
            id: uuidv4(),
            name: 'Андрей',
            prename: 'Петров',
            age: 22,
            photo: require('../assets/profilesPhoto/man2.png'),
            country: "США",
            height: "178 см",
            weight: "80 кг",
            eyeColor: "Голубые",
            hairColor: "Русые",
            goal: "Дружба и отношения",
            about: "Обожаю путешествовать и изучать новые культуры.",
            category: "lookingForGirlfriend",
        },
        {
            id: uuidv4(),
            name: 'Саша',
            prename: 'Петров',
            age: 38,
            photo: require('../assets/profilesPhoto/man3.png'),
            country: "США",
            height: "180 см",
            weight: "85 кг",
            eyeColor: "Серые",
            hairColor: "Темные",
            goal: "Дружба и серьезные отношения",
            about: "Я занимаюсь бизнесом и люблю спорт, особенно бег.",
            category: "lookingForGirlfriend",
        },
        {
            id: uuidv4(),
            name: 'Максим',
            prename: 'Петров',
            age: 19,
            photo: require('../assets/profilesPhoto/man4.png'),
            country: "США",
            height: "175 см",
            weight: "70 кг",
            eyeColor: "Карие",
            hairColor: "Каштановые",
            goal: "Легкие отношения",
            about: "Я студент, люблю музыку и вечеринки.",
            category: "lookingForGirlfriend",
        },
        {
            id: uuidv4(),
            name: 'Игорь',
            prename: 'Петров',
            age: 24,
            photo: require('../assets/profilesPhoto/man5.png'),
            country: "США",
            height: "182 см",
            weight: "78 кг",
            eyeColor: "Зеленые",
            hairColor: "Черные",
            goal: "Серьезные отношения",
            about: "Работаю дизайнером, увлекаюсь искусством и кино.",
            category: "lookingForGirlfriend",
        },
    ]
}

const usersProfiles = createSlice({
    name: 'usersProfiles',
    initialState,
    reducers: {
        setUsers: (state, action) => {
            state.users = state.payload
        },
        addUserToCategory: (state, action) => {
            const { category, user } = action.payload;
            if (state.users[category]) {
                state.users[category].push(user)
            } else {
                state.users[category] = [user]
            }
        },

    },
});

export const { setUsers, addUserToCategory, prevUser, nextUser } = usersProfiles.actions;
export default usersProfiles.reducer;
